# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ProductsListExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductsListExample

	pod 'RxSwift', '~> 5'
  pod 'RxDataSources', '~> 4'

  target 'ProductsListExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductsListExampleUITests' do
    # Pods for testing
  end

end
